[package]
name = "jellyfin-tui"
version = "0.2.1"
edition = "2021"

[dependencies]
reqwest = { version = "*", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
crossbeam = "0.8.4"
serde_yaml = "0.9.34"
libmpv = { path = "./libmpv-rs" }
ratatui = "0.28.0"
crossterm = "0.28.1"
ratatui-image = "1.0.5"
image = "0.25.2"
dirs = "5.0.1"
chrono = "0.4"
#souvlaki = "0.7.3"
souvlaki = { version = "0.7.3", default-features = false, features = ["use_zbus"] }
