[package]
name = "jellyfin-tui"
version = "1.0.2"
edition = "2021"

[dependencies]
reqwest = { version = "*", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
crossbeam = "0.8.4"
serde_yaml = "0.9.34"
libmpv2 = { version = "4.1.0" }
ratatui = "0.29.0"
crossterm = "0.28.1"
ratatui-image = { version = "3.0.0", default-features = false, features = ["crossterm"] }
image = { version = "0.25.5", default-features = false, features = ["jpeg", "png", "webp"] }
dirs = "5.0.1"
chrono = "0.4"
souvlaki = { version = "0.7.3", default-features = false, features = ["use_zbus"] }
color-thief = "0.2"